#!/bin/bash

set -e

mkdir -p /etc/nginx/vhosts.d
echo "#DO NOT EDIT THIS FILE (AUTOGENERATED)" > /etc/nginx/conf.d/http_vars.conf
echo "#DO NOT EDIT THIS FILE (AUTOGENERATED)" > /etc/nginx/vhosts.d/default.conf
echo "server {listen 80; return 404;}" >> /etc/nginx/vhosts.d/default.conf

for VH in `env | grep "VH_"`; do
    ENV=`echo $VH | awk -F "=" '{print $1}'`
    HOST=`echo $ENV | awk -F "_" '{print $2}'`
    TO_HOST=`echo $VH | awk -F "=" '{print $2}'`
    HOST_FILE=/etc/nginx/vhosts.d/host-$HOST.conf
    HOST_INC_FILE=/etc/nginx/vhosts.d/host-$HOST.inc
    echo "#DO NOT EDIT THIS FILE (AUTOGENERATED)" > $HOST_FILE
    if [ -f "$HOST_INC_FILE" ]; then
	echo "server {listen 80; server_name $HOST; include $HOST_INC_FILE; }" >> $HOST_FILE
    else
	echo "server {listen 80; server_name $HOST; location / { proxy_pass $TO_HOST; } }" >> $HOST_FILE
    fi;
done;

for SET_HTTP in `env | grep "SET_HTTP_"`; do
    ENV=`echo $SET_HTTP | awk -F "=" '{print $1}'`
    VALUE=`echo $SET_HTTP | awk -F "=" '{print $2}'`
    echo "${ENV:9} $VALUE;" >> /etc/nginx/conf.d/http_vars.conf
done;

exec "$@"
